name: onebuttonpong
base: core18 # the base snap is the execution environment for this snap
version: '0.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single button pong
description: |
  Press space to elevate your bat to protect your goal

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  game:
    plugin: autotools
    source: .
    configflags: [ --prefix=/usr ]
    build-packages:
      - build-essential
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libogg-dev
      - libvorbis-dev
      - libaudiofile-dev
      - libpulse-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libgl1-mesa-glx
      - libglu1-mesa
      - libogg0
      - libvorbis0a
      - libvorbisfile3
      - libmad0
  cleanup:
    after: [game]
    plugin: nil
    build-snaps:
      - core18
      - gtk-common-themes
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gtk-common-themes" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done

apps:
  onebuttonpong:
    command: pong
    plugs: [ audio-playback, desktop, opengl, unity7 ]
    extensions: [gnome-3-28]

layout:
  /usr/share/pong:
    symlink: $SNAP/usr/share/pong
